[package]
name = "pixworker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
clap = { version = "4.5.49", features = ["derive"] }
dirs = "6.0.0"
half = "2.7.1"
reqwest = { version = "0.12.24", features = ["blocking"] }
tempfile = "3.23.0"
image = { version = "0.25", features = ["png", "jpeg"] }
ndarray = "0.17"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
ort = { version = "=2.0.0-rc.13", features = ["download-binaries", "copy-dylibs", "half", "ndarray"] }

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
ort = { version = "=2.0.0-rc.13", features = ["coreml"] }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
ort = { version = "=2.0.0-rc.13", features = ["cuda", "tensorrt"] }

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
ort = { version = "=2.0.0-rc.13", features = ["cuda", "tensorrt"] }
