[package]
name = "burn-inference"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "=0.21.0", default-features = false, features = ["std", "metal"] }
burn-store = "=0.21.0"
image = { version = "0.25", default-features = false, features = ["png"] }

[build-dependencies]
burn-onnx = "=0.21.0"
